# CREATE SCHEMA DBO;
# DROP TABLE demo;
# CREATE TABLE IF NOT EXISTS DBO.tempo(
#   id_Tempo int GENERATED ALWAYS as IDENTITY,
#   -- ele é nulo por padrão.  default é o valor padrão.
#   precip_pluviom real NULL DEFAULT(0),
#   temp_min int not NULL,
#   temp_max int not NULL,
#   dh_coleta TIMESTAMP NOT NULL,
#   id_cidade int not NULL,
#   CONSTRAINT tempo_pk PRIMARY KEY(id_Tempo),
#   CONSTRAINT cidade_fk FOREIGN KEY (id_cidade) REFERENCES DBO.cidade(id_cidade),
#   CONSTRAINT coleta_cidade_unique UNIQUE(dh_coleta, id_cidade)
# );
# CREATE TABLE IF NOT EXISTS DBO.tempocentral(
#   id_tempo INT NOT NULL,
#   codigo_central char(5) NOT NULL,
#   CONSTRAINT tempocentral_pk PRIMARY KEY(id_tempo, codigo_central),
#   CONSTRAINT tempo_fk FOREIGN KEY (id_tempo) REFERENCES DBO.tempo(id_Tempo),
#   CONSTRAINT central_fk FOREIGN KEY (codigo_central) REFERENCES DBO.central(codigo)
# );
# CREATE TABLE IF NOT EXISTS DBO.central(
#   codigo char(5) NOT NULL,
#   CONSTRAINT codigo_pk PRIMARY KEY(codigo)
#  );
# --if not exists --- é para evitar erros. se a tabela não existir ele só passa
# CREATE TABLE IF NOT EXISTS DBO.cidade(
#   -- ID int GENERATED BY DEFAULT, o sgbd atribui o id por padrão caso o cliente n tenha enviado o id. Se ele colocar, não dá erro. Sucessível a conflitos, a sequência do sgbd não acompanha o id do input.
#   -- id_cidade serial NOT NULL, age parecido com o by defaut
#   --o sgbd sempre vai gerar o valor
#   id_cidade int GENERATED ALWAYS AS IDENTITY,
#   nome VARCHAR(150) NOT NULL,
#   estado CHAR(2) NOT NULL,
#   CONSTRAINT cidade_pk PRIMARY KEY(id_cidade),
#   constraint nome_estado_unique UNIQUE(nome, estado)
# );
# CREATE TABLE IF NOT EXISTS DBO.localizacao(
#   id_cidade int NOT NULL,
#   latitude REAL NOT NULL,
#   longitude REAL NOT NULL,
#   CONSTRAINT localizacao_pk PRIMARY KEY(latitude, longitude),
#   CONSTRAINT cidade_unique UNIQUE(id_cidade),
#   CONSTRAINT cidade_fk FOREIGN KEY (id_cidade) REFERENCES DBO.cidade(id_cidade)
#   --             cidade é chave estrangeira e referencia seu próprio id.

# );
# -- SELECT 'ifrn'; retorna um valor do parâmetro, no caso, ele retorn a própria stringdbo.cidade
# --tipe cast converte um tipo para outro
# SELECT '0'::int;
# -- quantidade de caracteres de uma str
# SElECT OCTET_LENGTH('ifrn');
# SElECT OCTET_LENGTH('ifrn'::varchar(50)); -- limita o limite da string, porém ela não tem o tamanho limite
# SElECT OCTET_LENGTH('ifrn'::varchar(3));
# SElECT OCTET_LENGTH('ifrn'::char(50)); -- usa o espaço até o limite. independente do tamanho da string dele